### ISSUE TITLE
Copy buttons on code-blocks don't work on Linux

### ISSUE THREAD

**Issue by iamtew** [magneticio/vamp.io#56] opened 2016-10-28 08:26 UTC
The Copy buttons on the code-blocks in the documentation pages aren't working on my Linux laptop.

Tested with Firefox 51.0a2 and Chromium 53.0.2785.143.

**Comment by iamtew** [comment] 2016-10-28 08:29
Some non-Flash solutions that work fine:

- https://clipboardjs.com/
- https://davidwalsh.name/clipboard
- https://www.sitepoint.com/javascript-copy-to-clipboard/

**Comment by olafmol** [comment] 2016-10-28 10:09
let's choose one that works fine with Chrome, Safari, Firefox on Mac OS, Win, Linux and make an issue for it to replace the flash copy buttons with this

**Comment by dragoslav** [comment] 2016-10-28 12:45
let's not close this until we have the new issue created (or keep using this one).

**Comment by iamtew** [comment] 2016-12-07 14:44
Copy buttons works now, however I'm getting HTML encoded characters:
```
{
  &quotid": &quotelasticsearch",
  &quotinstances": 1,
  &quotcpus": 0.2,
  &quotmem": 1024.0,
  &quotcontainer": {
    &quotdocker": {
      &quotimage": &quotmagneticio/elastic:2.2",
      &quotnetwork": &quotHOST",
      &quotforcePullImage": true
    }
  },
  &quothealthChecks": [
    {
      &quotprotocol": &quotTCP",
      &quotgracePeriodSeconds": 30,
      &quotintervalSeconds": 10,
      &quottimeoutSeconds": 5,
      &quotport": 9200,
      &quotmaxConsecutiveFailures": 0
    }
  ]
}
```

**Comment by iamtew** [comment] 2016-12-07 14:55
Confirmed working in Firefox and Chromium on Linux.

**Comment by gggina** [comment] 2016-12-08 08:57
Not linux related, but I am getting the same as reported by @iamtew on mac in chrome

docker run --net=host \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v `docker-machine ssh default &quotwhich docker"`:/bin/docker \
           -v "/sys/fs/cgroup:/sys/fs/cgroup" \
           -e &quotDOCKER_HOST_IP=$(docker-machine ip default)" \
           magneticio/vamp-docker:0.9.1

**Comment by olafmol** [comment] 2016-12-08 10:30
@gggina cannot reproduce this on Mac+Chrome, could you tell what version of Mac OS, Chrome and what text block on what page? Also make sure your cache is disabled/refreshed.

**Comment by gggina** [comment] 2016-12-08 10:33
It's working for me now as well. Should have checked better before re-opening.

**Closed by gggina** 2016-12-08 10:33 UTC
